### ISSUE TITLE
Could not find mixer

### ISSUE THREAD

**Issue by janschoenherr** [ircmaxell/RandomLib#25]
Hi,

just tried to use the High Strength Generator and received an error with "Could not find mixer". Do you know what causes the issue?

Regards,
Jan

**Update:** Just noticed, that there are no High Strength mixer shipped by default.

**Comment by haydenk** [comment]
There actually is a mixer available. You have to make sure you have the mcrypt extension and libsodium-dev installed.

**Comment by Mathieudewet** [comment]
I have the same issue with mcrypt installed enable and libsodium-dev installed.
