### ISSUE TITLE
Version requirements cause conflict

### ISSUE THREAD

**Issue by shadowhand** [ircmaxell/RandomLib#41]
The current requirement for PHP 3.7 causes conflicts with many newer packages. Please remove it or change to `3.7 - 5.0`.

**Comment by ircmaxell** [comment]
I assume you mean PHPUnit, not PHP?

**Comment by shadowhand** [comment]
I do.

On Sat, Dec 12, 2015, 12:26 PM Anthony Ferrara <notifications@github.com>
wrote:

> I assume you mean PHPUnit, not PHP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ircmaxell/RandomLib/issues/41#issuecomment-164174392>.
>
-- 

Woody Gilk
http://about.me/shadowhand

**Comment by ircmaxell** [comment]
Fixed in master. Will roll a release soon
