### ISSUE TITLE
Upgrade composer dependency of SecurityLib to 1.1

### ISSUE THREAD

**Issue by cballou** [ircmaxell/RandomLib#52]
There's changes in SecurityLib 1.1 that would be nice to haves, i.e. Util functions.

I'm currently using RandomLib in a secure port of a popular Google Authenticator library and one of the drawbacks of relying on RandomLib is I can't take advantage of the newer `SecurityLib::Util` class. Specifically, I'd like access to `substr()`. 

For now, I'll just copy that method.

**Comment by ircmaxell** [comment]
SecurityLib dependency is set at 1.1 in master. WIll tag this soon.
