### ISSUE TITLE
Is the new Random\Randomizer::getBytesFromString a replacement for this lib?

### ISSUE THREAD

**Issue by garak** [ircmaxell/RandomLib#69]
Hello,
I've been using this library for some years, and recently I noticed that PHP just added a [getBytesFromString](https://www.php.net/manual/en/random-randomizer.getbytesfromstring.php) function.
So I was wondering if I could replace the usage of this library with that new native implementation.

Example of old code:

```php
<?php

$factory = new RandomLib\Factory;
$generator = $factory->getMediumStrengthGenerator();
$randomString = $generator->generateString(8, 'abcdefghijklmnopqrstuvwxyz0123456789');
```

example of possible replacement:

```php
<?php

$randomizer = new \Random\Randomizer();
$randomString = $randomizer->getBytesFromString('abcdefghijklmnopqrstuvwxyz0123456789', 8);
```

If so, what would be the matching strength of the generator?

**Comment by TimWolla** [comment]
> So I was wondering if I could replace the usage of this library with that new native implementation.

Yes.

> If so, what would be the matching strength of the generator?

`\Random\Engine\Secure` (which is also the default engine if you don't make a choice).
